export const mainDeployOrigin = '';
export const lines = (items) => items.join('\n');

export const projectDetails = [
  {
    id: 'caredoc',
    label: 'CareDoc',
    type: '복지 서류 도구',
    demoOrigin: mainDeployOrigin,
    demoPath: '/clones/caredoc/index.html?portfolio=1&v=20260525-0025',
    showcaseImage: '/showcase/caredoc.png',
    visualKind: 'desk',
    cardIntro: '일본 장애인 복지시설의 반복 서류 입력과 확인 과정을 줄이는 도구입니다.',
    teaser: lines([
      'CareDoc은 일본 장애인 복지시설에서',
      '',
      '같은 정보를 반복해서 작성하던 과정을',
      '조금 더 단순하게 만들고자 시작한 프로젝트입니다.',
    ]),
    detailIntro: lines([
      '감사를 위해 최종적으로는',
      '인쇄 후 서류 보관이 필요했기 때문에,',
      '기존 문서 흐름은 유지하면서',
      '반복 입력과 확인 과정을 줄이는 방향에',
      '집중했습니다.',
    ]),
    title: '복지시설 서류 작성을 한 흐름으로 정리한 웹 도구',
    summary: lines([
      'CareDoc은 일본 장애인 복지시설에서',
      '실제로 사용하던 서류 업무를 보며',
      '시작한 프로젝트입니다.',
      '',
      '감사를 위해 최종적으로는',
      '인쇄 후 서류 보관이 필요했기 때문에,',
      '기존 문서 흐름은 유지하면서',
      '반복 입력과 확인 과정을 줄이는 방향에',
      '집중했습니다.',
    ]),
    stack: ['React', 'PDF', 'SVG', '엑셀·워드 웹화'],
    problem: lines([
      '• 같은 정보를 여러 문서에',
      '  반복해서 작성해야 했음',
      '',
      '• 문서마다 내용을 다시 수정하거나',
      '  복사해야 했음',
      '',
      '• 가족관계도(제노그램)를',
      '  워드 도형으로 직접 만들어야 했음',
    ]),
    solution: lines([
      '• 입력된 이용자 정보를 저장하고,',
      '  여러 서류에 자동 반영되도록 구성함',
      '',
      '• 실제 작성 순서 기준으로',
      '  입력 흐름을 다시 정리함',
      '',
      '• 가족관계도를 입력 정보 기반으로',
      '  SVG 형태로 자동 생성되도록 구현함',
    ]),
    learned: lines([
      '단축키 중심의',
      '빠른 입력 흐름을 고민함',
      '',
      '실제 사용자는 클릭 방식에',
      '더 익숙함을 인지함',
      '',
      '기존 흐름을 유지하며',
      '반복 작업을 줄이는 방향에 집중함',
    ]),
    checkpoints: ['이용자 정보 입력 흐름', '가족관계도 SVG 렌더링', '제출용 PDF 출력 확인'],
    detail: ['엑셀·워드 기반 업무를 브라우저 입력 흐름으로 정리', '이용자 정보를 여러 문서 항목에 연결', '가족관계도를 SVG로 렌더링', '확인한 내용을 PDF 출력 흐름으로 연결'],
    demo: [
      ['이용자', '야마다 하나코 / 82세 / 요양 3등급'],
      ['문서 흐름', '회의록, 모니터링, 지원계획서 자동 반영'],
      ['출력', '가족관계도 SVG + PDF 준비 완료'],
    ],
    screenshots: [
      ['기존 서류 분석', lines([
        '복잡한 워드 서류에서 반복 입력과',
        '수기 작성 병목을 확인했습니다.',
      ]), '/project-shots/caredoc/01.jpg'],
      ['서류 입력 흐름 재구성', lines([
        '여러 문서에 흩어진 입력 항목을 정리해',
        '한 번 입력한 정보가 이어지도록 구성했습니다.',
      ]), '/project-shots/caredoc/02.jpg'],
      ['반복 문구 입력 개선', lines([
        '자주 쓰는 표현을 버튼과 단축키로 선택해',
        '반복 입력 부담을 줄였습니다.',
      ]), '/project-shots/caredoc/03.jpg'],
      ['업무 화면 단순화', lines([
        '사용자가 순서대로 따라가면 작성이 끝나도록',
        '입력 흐름을 단순하게 정리했습니다.',
      ]), '/project-shots/caredoc/04.jpg'],
      ['가족관계도 자동 렌더링', lines([
        '워드 도형으로 직접 만들던 가족관계도를',
        '입력값 기반 SVG로 자동 생성했습니다.',
      ]), '/project-shots/caredoc/05.jpg'],
      ['PDF 출력 흐름 구성', lines([
        '작성 내용을 최종 확인한 뒤',
        '제출용 PDF로 이어지도록 구성했습니다.',
      ]), '/project-shots/caredoc/06.jpg'],
    ],
  },
  {
    id: 'fixchecker',
    label: 'Subtitle Fix Checker',
    type: '자막 검수 보조 도구',
    demoOrigin: mainDeployOrigin,
    demoPath: '/clones/subtitle-fix-checker/index.html',
    showcaseImage: '/showcase/fixchecker.png',
    visualKind: 'browser',
    teaser: lines([
      'Subtitle Fix Checker는',
      '',
      '자막 검수 결과를 JSON 주문서 형태로 정리해,',
      'AI 재작업까지 이어지도록 만들고자',
      '시작한 프로젝트입니다.',
    ]),
    title: '자막 검수 판단을 작업지시서로 정리하는 도구',
    summary: lines([
      'Subtitle Fix Checker는',
      '빠른 자막 검수 이후,',
      '수정 내용을 JSON 주문서 형태로 정리해',
      'AI에게 다시 후단 작업을 요청하기 위해',
      '만든 도구입니다.',
    ]),
    stack: ['React', 'SRT', 'JSON', 'Markdown', 'CapCut'],
    problem: lines([
      '• AI 자동 자막 결과에',
      '  어색한 표현이 자주 발생했음',
      '',
      '• 자막 수정 시 확대·선택·수정을 반복하며,',
      '  잘못 조작하면 다시 작업해야 했음',
      '',
      '• AI를 2차로 사용해 수정하려 했지만,',
      '  시간큐 정보와 수정 내용을 다시 설명해야 했음',
    ]),
    solution: lines([
      '• MP4와 SRT를 함께 보며',
      '  단축키 하나로 시간큐와 수정 내용을 기록함',
      '',
      '• 검수한 시간큐와 수정 내용을',
      '  JSON 내부에 자동 기록되도록 구성함',
      '',
      '• 자주 쓰는 요청을 버튼화해',
      '  백그라운드에서 JSON에 자동 기록함',
    ]),
    learned: lines([
      'AI가 자막을 자동으로 수정해도,',
      '항상 원하는 결과가 나오지는 않았음',
      '',
      '↓',
      '',
      '사람이 빠르게 검수하고',
      '수정 방향을 정리할 흐름이 필요했음',
      '',
      '↓',
      '',
      '설명을 길게 적기보다,',
      '버튼 형태로 요청을 남기도록 구성함',
    ]),
    checkpoints: ['영상/SRT 드래그 앤 드롭', 'Tab 및 단축키 cue 기록', 'JSON 작업지시서 저장'],
    detail: ['영상과 SRT를 함께 불러오는 검수 화면', 'Tab/단축키로 문제 cue 기록', '수정모드에서 표현과 요청사항 확정', '미저장 항목 경고 후 JSON 작업지시서 저장'],
    demo: [
      ['Tab', '현재 cue 기록 + 영상 일시정지'],
      ['Q/W/A/S/D', '한국어·일본어 오류, 빠름·느림, 자막컷팅 표시'],
      ['저장', '요청사항과 cue 정보를 JSON으로 내보내기'],
    ],
    screenshots: [
      ['메인화면', '드래그 앤 드롭으로 영상과 SRT를 직관적으로 넣을 수 있습니다.', '/project-shots/fixchecker/01.jpg'],
      ['큐 슬롯', 'Tab이나 / 단축키로 영상을 보며 이상한 자막을 골라냅니다.', '/project-shots/fixchecker/02.jpg'],
      ['수정모드 진입', '선택된 큐에서 Enter를 입력하면 수정모드로 진입됩니다.', '/project-shots/fixchecker/03.jpg'],
      ['직접수정 모드', '표시한 cue의 표현과 요청사항을 확인하고 바로 고칠 수 있습니다.', '/project-shots/fixchecker/04.jpg'],
      ['큐 수정', '큐를 입력해 미리 지정된 효과를 넣어달라고 요청할 수 있습니다.', '/project-shots/fixchecker/05.jpg'],
      ['저장', lines([
        '작업 주문이 끝난 항목은 저장 상태로 확인합니다.',
        '수정하지 않은 항목은 저장 시점에 알려줍니다.',
      ]), '/project-shots/fixchecker/06.jpg'],
    ],
  },
  {
    id: 'lucid',
    label: 'Lucid',
    type: '부트캠프 학습 플랫폼',
    demoOrigin: mainDeployOrigin,
    demoPath: '/clones/lucid/index.html#/login',
    showcaseImage: '/showcase/lucid.png',
    visualKind: 'shelf',
    teaser: lines([
      'Lucid는 AI로 공부하는 시대에,',
      '',
      '학생은 몰입을 유지하고,',
      '강사는 이해도와 학습 상태를 데이터로 확인할 수 있는',
      '환경을 만들고자 시작한 프로젝트입니다.',
    ]),
    title: '수업 코드와 학습 상태를 한 화면에 모은 학습 플랫폼',
    summary: lines([
      '강사의 GitHub 코드 자료를 Monaco Editor에서 확인하고,',
      '튜터 채팅, 질문, 퀴즈, 메모, 타자 연습, 학습 기록을 같은 흐름에서 다룹니다.',
    ]),
    stack: ['React', 'Vite', 'Firebase', 'Vercel', 'GitHub API', 'Monaco Editor'],
    problem: lines([
      '• AI로 정답은 쉽게 얻지만',
      '  무엇을 모르는지 파악하기 어려웠음',
      '',
      '• 번역, 검색, 메모 등',
      '  여러 도구를 오가야 했음',
      '',
      '• 강사는 학생이 어디서 막히는지',
      '  파악하기 어려웠음',
      '',
      '• 학생 상태를 확인할 수 있는',
      '  데이터가 부족했음',
    ]),
    solution: lines([
      '• 코드, 메모, 문제 풀이를',
      '  하나의 학습 환경으로 통합함',
      '',
      '• 현재 코드 맥락을 기반으로',
      '  AI 튜터가 설명하도록 구성함',
      '',
      '• 레벨과 출석 데이터를 기반으로',
      '  학생 상태를 시각화함',
      '',
      '• GitHub 자료를 연동해',
      '  복습과 질문이 이어지도록 구성함',
    ]),
    learned: lines([
      '학습자가 언제 몰입에서 벗어나는지',
      '먼저 고민함',
      '',
      '↓',
      '',
      '검색, 번역, 메모 등',
      '도구를 오가는 순간에 주목함',
      '',
      '↓',
      '',
      '사전 기능, AI 검색, 타자 연습 등',
      '몰입을 유지하는 기능을 구성함',
      '',
      '↓',
      '',
      '이 흐름을 하나로 묶어',
      '학습이 끊기지 않는 시스템으로 만들고자 함',
    ]),
    checkpoints: ['GitHub 코드와 Monaco Editor 열람', '튜터 채팅/질문/퀴즈/메모/타자 연습', '학생·관리자 상태와 XP·스트릭·LP·원두 확인'],
    detail: ['GitHub 코드 불러오기와 Monaco Editor 코드 열람', '튜터 채팅과 질문 흐름 연결', '퀴즈·메모·타자 연습으로 복습 흐름 구성', 'Firebase 기반 학생·관리자 화면과 XP, 스트릭, LP, 원두 기록'],
    demo: [
      ['코드', '강사 GitHub 자료를 Monaco Editor로 확인'],
      ['학습', '튜터 채팅, 질문, 퀴즈, 메모, 타자 연습으로 복습'],
      ['기록', 'XP, 스트릭, LP와 원두로 학습 상태 확인'],
    ],
    screenshots: [
      ['홈화면', '스트릭과 원두 기록으로 학습 지속 상태를 확인할 수 있습니다.', '/project-shots/lucid/01.jpg'],
      ['코드 학습 화면', '불러온 코드를 보며 튜터 채팅과 질문 흐름을 함께 사용할 수 있습니다.', '/project-shots/lucid/02.jpg'],
      ['강사 GitHub 불러오기', '등록된 강사의 GitHub 자료를 수업 흐름에 맞춰 불러옵니다.', '/project-shots/lucid/03.jpg'],
      ['코드노트에 불러오기', 'GitHub API로 강의 내용에 접근해 선택한 챕터를 불러올 수 있습니다.', '/project-shots/lucid/04.jpg'],
      ['모르는 단어 바로 체크', '학습 중 모르는 기술용어와 영어단어를 바로 확인할 수 있습니다.', '/project-shots/lucid/05.jpg'],
      ['문제 풀이', '복습한 코드를 바탕으로 퀴즈를 풀며 이해도를 확인합니다.', '/project-shots/lucid/06.jpg'],
    ],
  },
  {
    id: 'reallife',
    label: 'RealLife',
    type: '생활 시뮬레이션',
    demoOrigin: mainDeployOrigin,
    demoPath: '/clones/reallife/index.html',
    showcaseImage: '/showcase/reallife.png',
    visualKind: 'document',
    teaser: lines([
      'RealLife는 AI 코딩으로',
      '게임을 어디까지 구현할 수 있는지 실험하며,',
      '',
      '경제 개념을 경험으로 전달해보고자',
      '시작한 프로젝트입니다.',
    ]),
    title: '선택과 정산 흐름을 보여주는 생활 시뮬레이션 게임',
    summary: '턴 진행, 자산 변화, 선택 결과를 화면에서 확인하며 상태 흐름을 실습한 프로젝트입니다.',
    stack: ['React', '게임 화면', '상태 흐름', '룰 기반 진행'],
    briefLabels: ['시작한 이유', '구현한 것', '실험을 통해 인지한 것'],
    problem: lines([
      '• AI 코딩으로 상상한 게임을',
      '  어디까지 구현할 수 있을지 궁금했음',
      '',
      '• 관련 없는 요소들을 조합하면',
      '  어떤 결과가 나올지 궁금했음',
      '',
      '• 경제 개념을 설명보다 경험으로',
      '  전달할 수 있을지 궁금했음',
    ]),
    solution: lines([
      '• 대출, 이자, 생활비 등',
      '  경제 요소를 게임 규칙에 반영함',
      '',
      '• 주사위, 룰렛, 사회자 멘트를 통해',
      '  게임 진행 상황을 전달하도록 구성함',
      '',
      '• 말 이동 구간 확대 및 축소 등',
      '  카메라 연출을 적용해 몰입감을 강화함',
    ]),
    learned: lines([
      '• 몰입감은 화려한 효과보다',
      '  시선과 생각 흐름의 표현에서 나온다는 점을 인지',
      '',
      '• 어느 정도 구현이 진행된 뒤,',
      '  다시 기획부터 돌아봐야 함을 인지',
      '',
      '• AI는 생각보다 많은 것을 구현할 수 있었고,',
      '  얼마나 구체적으로 상상하느냐가 중요함을 인지',
    ]),
    checkpoints: ['턴 진행 안내', '매입·통행료·대출 선택', '현금과 자산 변화 피드백'],
    detail: ['턴 진행과 이벤트 안내', '현금과 자산 변화 표시', '매입·통행료·대출 선택 흐름', '게임 UI와 상태 변경 로직 실습'],
    demo: [
      ['1턴', '알바 제안 수락 / 체력 -8 / 현금 +70,000'],
      ['2턴', '자격증 공부 / 집중도 +12 / 시간 -3'],
      ['결과', '생활비와 성장 선택지를 비교'],
    ],
    screenshots: [
      ['권리증 화면', '임대료와 보유 자산 정보를 직관적으로 보여줍니다.', '/project-shots/reallife/01.jpg'],
      ['타인의 땅을 밟았을 때', '사회자 멘트와 애니메이션으로 통행료 상황을 보여줍니다.', '/project-shots/reallife/02.jpg'],
      ['차례 안내', '턴이 넘어오면 차례 안내가 나갑니다.', '/project-shots/reallife/03.jpg'],
      ['정산 연출', '누가 누구의 땅을 밟았는지 한 화면에서 확인합니다.', '/project-shots/reallife/04.jpg'],
      ['매입 선택', lines([
        '부동산 도착 시 매입과 스킵을 선택합니다.',
        '매입하면 보유 현금이 바로 줄어드는',
        '정산 액션이 표시됩니다.',
      ]), '/project-shots/reallife/05.jpg'],
      ['대출 기능', lines([
        '조건에 맞으면 담보대출과 신용대출을 선택할 수 있습니다.',
        '대출 이후에는 매 턴 이자를 지급해야 하므로',
        '현금 흐름 확인이 중요합니다.',
      ]), '/project-shots/reallife/06.jpg'],
    ],
  },
];

export const experienceItems = [
  {
    id: 'career-crm',
    label: '경력',
    period: '2016.01 ~ 현재',
    markerTitle: ['고객 상담', '& 유지 업무 경험'],
    title: '사람은 항상 합리적으로 움직이지 않았다',
    body: lines([
      '8년간 고객 응대 업무를 하며,',
      '사람은 단순히 더 좋은 조건만으로',
      '선택하지 않는다는 점을 많이 느꼈습니다.',
      '',
      '더 좋은 선택지가 있어도',
      '익숙한 흐름을 유지하려는 경우도 많았습니다.',
      '',
      '이 경험은 이후 사용자 입장에서',
      '얼마나 자연스럽고 부담 없이 이어지는지가',
      '중요하다는 관심으로 이어졌습니다.',
    ]),
  },
  {
    id: 'career-japan',
    label: '해외연수',
    period: '2018.04 ~ 2019.10',
    markerTitle: ['일본 유학', '& 워킹홀리데이 경험'],
    title: '표현 방식보다 중요한 건 흐름과 감정이었다',
    body: lines([
      '일본 워킹홀리데이와 유학원 생활을 하며,',
      '현지 문화와 생활 언어를',
      '직접 경험했습니다.',
      '',
      '한국과 일본은 표현 방식과 분위기는 달랐지만,',
      '사람이 불편함을 느끼고 반응하는 감정 자체는',
      '크게 다르지 않다는 점이 인상 깊었습니다.',
      '',
      '이 경험은 이후 사용자 반응과 흐름을',
      '더 세밀하게 관찰하는 관심으로 이어졌습니다.',
    ]),
  },
  {
    id: 'career-education',
    label: '교육 이수',
    period: '2025.09 ~ 2026.02',
    markerTitle: ['AI·풀스택 과정', '& 프로젝트 경험'],
    title: '작은 변화 하나가 전체 경험을 바꾼다',
    body: lines([
      'RAG·AI 기반 풀스택 개발 과정을 통해',
      'Java, Spring Boot, MySQL, React 기반의',
      '웹 서비스 구조를 학습했습니다.',
      '',
      '팀 프로젝트에서는 레시피 추천 서비스의',
      '데이터 정규화 문제를 맡으며,',
      '사용자 흐름과 데이터 구조를 함께 고민했습니다.',
      '',
      '이후에는 반복되는 작업과 사용자 흐름을',
      '직접 구현하고 정리하는 연습을 이어가고 있습니다.',
    ]),
  },
];

export const resumeIntro = lines([
  '고객과 가까운 자리에서 일하며 같은 불편이 여러 번 반복되는 순간을 자주 봤습니다. 그 경험은 기능을 많이 넣기보다 사용자가 어디에서 멈추는지 먼저 찾는 습관으로 이어졌습니다.',
  '',
  '풀스택 개발 교육에서는 Java, Servlet/JSP, Spring Boot, Spring Security, JWT, MyBatis, MySQL을 학습했고, 프론트엔드에서는 HTML/CSS 기초와 React, Vite, Router, Axios, Zustand, React Query를 다뤘습니다. 팀 프로젝트를 거치며 기능이 동작해도 사용자가 헷갈리면 좋은 흐름이 아니라는 점을 배웠습니다.',
  '',
  '교육 이후에는 CareDoc, Subtitle Fix Checker, Lucid처럼 작은 업무 병목을 웹 도구로 바꾸는 프로젝트를 이어가고 있습니다. CareDoc은 복지시설 서류 작성 흐름을, Subtitle Fix Checker는 자막 검수 판단을, Lucid는 수업 코드와 학습 상태 확인 흐름을 정리하는 데 초점을 맞췄습니다.',
  '',
  'AI 도구는 문제를 나누고 작업 순서를 점검하는 보조 수단으로 사용합니다. 앞으로도 사용자가 왜 불편한지부터 확인하고, 바로 쓸 수 있는 작은 개선을 끝까지 완성하는 개발자가 되고 싶습니다.',
]);

export const profileFacts = [
  ['이름', '최혁준'],
  ['방향', '불편한 반복을 줄이는 개발자'],
  ['학습', 'Java · Spring Boot · React · MySQL · HTML/CSS'],
  ['도구', 'React · Vite · Firebase · Vercel · GitHub API'],
  ['경험', lines([
    '고객 응대 8년 이상',
    '일본 워킹홀리데이 1년 · 유학원 6개월',
    '일본어권 가족과 생활',
  ])],
];
